# Generated by Django 4.1.7 on 2023-02-27 09:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, upload_to='images/', verbose_name='Upload category image')),
                ('name', models.CharField(max_length=100, verbose_name='Write category name')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('statename', models.CharField(max_length=100, verbose_name='Product state name')),
                ('factoryname', models.CharField(max_length=100, verbose_name='Product factory name')),
                ('size', models.CharField(max_length=100, verbose_name='Product size')),
                ('material', models.CharField(max_length=100, verbose_name='Product material')),
                ('info', ckeditor.fields.RichTextField(verbose_name='Product about info')),
                ('posterdekor', models.ImageField(blank=True, upload_to='images/', verbose_name='Products dekor upload image')),
                ('posterpol', models.ImageField(blank=True, upload_to='images/', verbose_name='Product pol upload image')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posterinfo', to='product.products')),
            ],
        ),
    ]
